import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import YAML from 'yaml';
import type { ProjectConfig, SourceConfig, TargetSpec } from './types.js';

export const CONFIG_FILE = '.agentkit.yaml';
export const LOCK_FILE = '.agentkit.lock.json';
export const TARGETS_FILE = 'targets.yaml';

export function hasProjectConfig(root: string): boolean {
  return existsSync(join(root, CONFIG_FILE));
}

export function loadProjectConfig(root: string): ProjectConfig {
  const path = join(root, CONFIG_FILE);
  if (!existsSync(path)) throw new Error(`${CONFIG_FILE} not found in ${root}. Run "npx agent-kit" to create it.`);
  const cfg = (YAML.parse(readFileSync(path, 'utf8')) ?? {}) as ProjectConfig;
  if (!Array.isArray(cfg.targets)) cfg.targets = [];
  return cfg;
}

export function saveProjectConfig(root: string, cfg: ProjectConfig): void {
  const header =
    '# Generated by agent-kit. Re-run "npx agent-kit" to change interactively,\n' +
    '# or edit by hand and run "npx agent-kit sync".\n';
  writeFileSync(join(root, CONFIG_FILE), header + YAML.stringify(cfg, { lineWidth: 0 }));
}

/** Own sources, accepting the legacy single-source form. */
export function ownSources(cfg: ProjectConfig): SourceConfig[] {
  const list = [...(cfg.sources ?? [])];
  if (cfg.source) list.unshift({ source: cfg.source, ref: cfg.ref, include: cfg.include });
  return list;
}

export function readSourceTargets(sourceDir: string): Record<string, TargetSpec> {
  const path = join(sourceDir, TARGETS_FILE);
  return existsSync(path) ? ((YAML.parse(readFileSync(path, 'utf8'))?.targets ?? {}) as Record<string, TargetSpec>) : {};
}

export function resolveTargets(all: Record<string, TargetSpec>, ids: string[]): Array<[string, TargetSpec]> {
  const unknown = ids.filter((id) => !all[id]);
  if (unknown.length) {
    const known = Object.keys(all).join(', ') || '(none defined)';
    throw new Error(`Unknown target(s): ${unknown.join(', ')}. Known: ${known}`);
  }
  return ids.map((id) => [id, all[id]]);
}
